name: Add Label

on:
  issues:
    types: unlabeled

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.label.name == 'haha'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['stage/need-attention']
            })
